[2023-06-14T14:17:10.708+0000] {processor.py:157} INFO - Started process (PID=1950) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:17:10.709+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:17:10.711+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:10.711+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:17:10.714+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:10.714+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:17:10.714+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:17:10.714+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:17:10.715+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:17:10.726+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-06-14T14:19:33.291+0000] {processor.py:157} INFO - Started process (PID=4136) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:19:33.293+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:19:33.295+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:19:33.295+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:19:33.298+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:19:33.298+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:19:33.299+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:19:33.299+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:19:33.299+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:19:33.313+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-06-14T14:20:31.755+0000] {processor.py:157} INFO - Started process (PID=4297) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:20:31.757+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:20:31.759+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:31.759+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:20:31.762+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:31.762+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:20:31.762+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:20:31.762+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:20:31.763+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:20:31.775+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:21:26.061+0000] {processor.py:157} INFO - Started process (PID=4453) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:21:26.063+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:21:26.065+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:21:26.065+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:21:26.068+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:21:26.068+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:21:26.068+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:21:26.068+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:21:26.069+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:21:26.081+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:22:19.131+0000] {processor.py:157} INFO - Started process (PID=4615) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:22:19.132+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:22:19.135+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:19.135+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:22:19.138+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:19.137+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:22:19.138+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:22:19.138+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:22:19.138+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:22:19.150+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:23:11.775+0000] {processor.py:157} INFO - Started process (PID=4773) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:11.777+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:23:11.779+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:11.779+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:11.782+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:11.782+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:23:11.782+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:11.782+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:23:11.782+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:11.794+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:23:59.882+0000] {processor.py:157} INFO - Started process (PID=5027) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:59.883+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:23:59.886+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:59.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:59.889+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:59.888+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:23:59.889+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:23:59.889+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:23:59.889+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:23:59.902+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-06-14T14:24:50.867+0000] {processor.py:157} INFO - Started process (PID=5121) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:24:50.868+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:24:50.871+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:50.870+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:24:50.874+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:50.873+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:24:50.874+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:24:50.874+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:24:50.874+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:24:50.885+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:25:38.151+0000] {processor.py:157} INFO - Started process (PID=5233) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:25:38.153+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:25:38.155+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:25:38.155+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:25:38.158+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:25:38.158+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:25:38.158+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:25:38.158+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:25:38.159+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:25:38.171+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:26:33.197+0000] {processor.py:157} INFO - Started process (PID=5392) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:26:33.199+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:26:33.201+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:33.201+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:26:33.204+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:33.204+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:26:33.204+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:26:33.204+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:26:33.205+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:26:33.216+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:27:24.832+0000] {processor.py:157} INFO - Started process (PID=5550) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:27:24.834+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:27:24.836+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:24.836+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:27:24.839+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:24.839+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:27:24.839+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:27:24.839+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:27:24.840+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:27:24.851+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:28:18.054+0000] {processor.py:157} INFO - Started process (PID=5708) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:28:18.056+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:28:18.058+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:28:18.058+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:28:18.061+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:28:18.061+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:28:18.061+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:28:18.061+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:28:18.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:28:18.073+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:29:09.521+0000] {processor.py:157} INFO - Started process (PID=5967) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:29:09.522+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:29:09.525+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:09.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:29:09.528+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:09.527+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:29:09.528+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:29:09.528+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:29:09.528+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:29:09.540+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:30:00.891+0000] {processor.py:157} INFO - Started process (PID=6122) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:00.893+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:30:00.895+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:00.895+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:00.898+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:00.898+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:30:00.898+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:00.898+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:30:00.899+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:00.910+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:30:57.473+0000] {processor.py:157} INFO - Started process (PID=6281) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:57.474+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:30:57.476+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:57.476+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:57.479+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:57.479+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:30:57.479+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:30:57.479+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:30:57.480+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:30:57.491+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-06-14T14:31:49.359+0000] {processor.py:157} INFO - Started process (PID=6335) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:31:49.360+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:31:49.363+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:49.362+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:31:49.366+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:49.365+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:31:49.366+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:31:49.366+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:31:49.366+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:31:49.378+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:32:40.999+0000] {processor.py:157} INFO - Started process (PID=6497) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:32:41.000+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:32:41.003+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:32:41.003+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:32:41.006+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:32:41.005+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:32:41.006+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:32:41.006+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:32:41.006+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:32:41.018+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:33:28.994+0000] {processor.py:157} INFO - Started process (PID=6650) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:33:28.998+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:33:29.000+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:29.000+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:33:29.003+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:29.003+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:33:29.004+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:33:29.003+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:33:29.004+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:33:29.015+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-06-14T14:34:24.331+0000] {processor.py:157} INFO - Started process (PID=6909) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:34:24.333+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:34:24.335+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:24.335+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:34:24.338+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:24.338+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:34:24.339+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:34:24.339+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:34:24.339+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:34:24.351+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:35:16.070+0000] {processor.py:157} INFO - Started process (PID=7069) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:35:16.071+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:35:16.074+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:16.073+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:35:16.077+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:16.076+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:35:16.077+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:35:16.077+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:35:16.077+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:35:16.089+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:36:07.782+0000] {processor.py:157} INFO - Started process (PID=7226) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:36:07.784+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:36:07.786+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:36:07.786+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:36:07.789+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:36:07.789+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:36:07.789+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:36:07.789+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:36:07.789+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:36:07.802+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:37:00.894+0000] {processor.py:157} INFO - Started process (PID=7382) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:00.896+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:37:00.898+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:00.898+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:00.901+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:00.901+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:37:00.902+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:00.901+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:37:00.902+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:00.913+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:37:52.762+0000] {processor.py:157} INFO - Started process (PID=7543) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:52.764+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:37:52.766+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:52.766+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:52.769+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:52.769+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:37:52.769+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:37:52.769+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:37:52.770+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:37:52.781+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:38:42.859+0000] {processor.py:157} INFO - Started process (PID=7595) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:38:42.860+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:38:42.862+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:42.862+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:38:42.865+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:42.865+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:38:42.865+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:38:42.865+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:38:42.866+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:38:42.877+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:39:29.058+0000] {processor.py:157} INFO - Started process (PID=7746) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:39:29.059+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:39:29.062+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:29.061+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:39:29.065+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:29.064+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:39:29.065+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:39:29.065+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:39:29.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:39:29.077+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:40:22.340+0000] {processor.py:157} INFO - Started process (PID=7902) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:40:22.342+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:40:22.344+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:40:22.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:40:22.348+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:40:22.347+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:40:22.348+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:40:22.348+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:40:22.348+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:40:22.360+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:41:17.925+0000] {processor.py:157} INFO - Started process (PID=8060) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:41:17.926+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:41:17.929+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:17.929+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:41:17.932+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:17.931+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:41:17.932+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:41:17.932+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:41:17.932+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:41:17.944+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:42:10.618+0000] {processor.py:157} INFO - Started process (PID=8222) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:42:10.620+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:42:10.622+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:10.622+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:42:10.625+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:10.625+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:42:10.625+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:42:10.625+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:42:10.626+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:42:10.637+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:43:07.154+0000] {processor.py:157} INFO - Started process (PID=8380) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:43:07.155+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:43:07.158+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:43:07.158+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:43:07.161+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:43:07.160+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:43:07.161+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:43:07.161+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:43:07.161+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:43:07.173+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:44:03.966+0000] {processor.py:157} INFO - Started process (PID=8640) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:03.967+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:44:03.969+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:03.969+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:03.972+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:03.972+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:44:03.973+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:03.972+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:44:03.973+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:03.984+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:44:57.206+0000] {processor.py:157} INFO - Started process (PID=8798) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:57.207+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:44:57.209+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:57.209+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:57.213+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:57.212+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:44:57.213+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:44:57.213+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:44:57.213+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:44:57.225+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:45:53.912+0000] {processor.py:157} INFO - Started process (PID=8958) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:45:53.913+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:45:53.916+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:45:53.915+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:45:53.919+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:45:53.918+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:45:53.919+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:45:53.919+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:45:53.919+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:45:53.931+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:46:48.350+0000] {processor.py:157} INFO - Started process (PID=9014) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:46:48.352+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:46:48.354+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:48.354+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:46:48.357+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:48.357+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:46:48.358+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:46:48.357+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:46:48.358+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:46:48.370+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:47:41.069+0000] {processor.py:157} INFO - Started process (PID=9173) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:47:41.070+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:47:41.073+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:41.073+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:47:41.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:41.075+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:47:41.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:47:41.076+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:47:41.076+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:47:41.088+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:48:31.509+0000] {processor.py:157} INFO - Started process (PID=9327) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:48:31.510+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:48:31.513+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:31.512+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:48:31.516+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:31.515+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:48:31.516+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:48:31.516+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:48:31.516+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:48:31.528+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:49:28.345+0000] {processor.py:157} INFO - Started process (PID=9588) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:49:28.347+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:49:28.349+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:49:28.349+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:49:28.352+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:49:28.352+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:49:28.352+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:49:28.352+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:49:28.353+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:49:28.364+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:50:24.511+0000] {processor.py:157} INFO - Started process (PID=9747) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:50:24.513+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:50:24.515+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:24.515+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:50:24.518+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:24.518+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:50:24.518+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:50:24.518+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:50:24.519+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:50:24.530+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:51:15.718+0000] {processor.py:157} INFO - Started process (PID=9902) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:51:15.720+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:51:15.722+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:15.722+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:51:15.725+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:15.725+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:51:15.725+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:51:15.725+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:51:15.726+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:51:15.737+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:52:01.146+0000] {processor.py:157} INFO - Started process (PID=10055) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:01.148+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:52:01.150+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:01.150+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:01.153+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:01.153+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:52:01.153+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:01.153+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:52:01.154+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:01.166+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:52:53.758+0000] {processor.py:157} INFO - Started process (PID=10214) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:53.759+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:52:53.762+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:53.762+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:53.765+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:53.764+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:52:53.765+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:52:53.765+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:52:53.765+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:52:53.777+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-06-14T14:53:45.874+0000] {processor.py:157} INFO - Started process (PID=10267) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:53:45.876+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:53:45.878+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:45.878+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:53:45.881+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:45.881+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:53:45.881+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:53:45.881+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:53:45.882+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:53:45.894+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T14:54:40.445+0000] {processor.py:157} INFO - Started process (PID=10529) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:54:40.447+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:54:40.449+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:40.449+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:54:40.452+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:40.451+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:54:40.452+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:54:40.452+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:54:40.452+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:54:40.464+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-06-14T14:55:32.487+0000] {processor.py:157} INFO - Started process (PID=10786) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:55:32.488+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:55:32.490+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:32.490+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:55:32.493+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:32.493+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:55:32.494+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:55:32.494+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:55:32.494+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:55:32.506+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:56:24.325+0000] {processor.py:157} INFO - Started process (PID=10943) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:56:24.327+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:56:24.329+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:56:24.329+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:56:24.332+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:56:24.332+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:56:24.332+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:56:24.332+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:56:24.333+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:56:24.345+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:57:14.710+0000] {processor.py:157} INFO - Started process (PID=11103) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:57:14.711+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:57:14.713+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:14.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:57:14.716+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:14.716+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:57:14.717+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:57:14.717+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:57:14.717+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:57:14.728+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-06-14T14:58:06.192+0000] {processor.py:157} INFO - Started process (PID=11257) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:06.193+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:58:06.196+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:06.195+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:06.199+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:06.198+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:58:06.199+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:06.199+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:58:06.199+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:06.211+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:58:56.628+0000] {processor.py:157} INFO - Started process (PID=11452) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:56.629+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:58:56.631+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:56.631+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:56.635+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:56.634+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:58:56.635+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:58:56.635+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:58:56.635+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:58:56.647+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T14:59:43.753+0000] {processor.py:157} INFO - Started process (PID=11563) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:59:43.755+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T14:59:43.757+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:59:43.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:59:43.760+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:59:43.759+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T14:59:43.760+0000] {logging_mixin.py:149} INFO - [2023-06-14T14:59:43.760+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T14:59:43.760+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T14:59:43.772+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:00:33.779+0000] {processor.py:157} INFO - Started process (PID=11719) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:00:33.781+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:00:33.783+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:33.783+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:00:33.786+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:33.786+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:00:33.786+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:00:33.786+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:00:33.787+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:00:33.798+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:01:26.121+0000] {processor.py:157} INFO - Started process (PID=11877) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:01:26.123+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:01:26.125+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:26.125+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:01:26.128+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:26.127+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:01:26.128+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:01:26.128+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:01:26.128+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:01:26.140+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:02:16.463+0000] {processor.py:157} INFO - Started process (PID=12040) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:02:16.464+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:02:16.467+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:16.467+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:02:16.470+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:16.469+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:02:16.470+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:02:16.470+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:02:16.470+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:02:16.483+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T15:03:07.539+0000] {processor.py:157} INFO - Started process (PID=12298) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:07.540+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:03:07.543+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:07.543+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:07.546+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:07.546+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:03:07.547+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:07.547+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:03:07.547+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:07.559+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-06-14T15:03:59.613+0000] {processor.py:157} INFO - Started process (PID=12558) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:59.615+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:03:59.617+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:59.617+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:59.620+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:59.619+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:03:59.620+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:03:59.620+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:03:59.620+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:03:59.632+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:04:52.278+0000] {processor.py:157} INFO - Started process (PID=12651) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:04:52.279+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:04:52.282+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:52.282+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:04:52.285+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:52.284+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:04:52.285+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:04:52.285+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:04:52.285+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:04:52.301+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-06-14T15:05:49.078+0000] {processor.py:157} INFO - Started process (PID=13008) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:05:49.079+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:05:49.082+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:49.081+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:05:49.085+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:49.084+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:05:49.085+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:05:49.085+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:05:49.085+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:05:49.098+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T15:06:41.924+0000] {processor.py:157} INFO - Started process (PID=13165) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:06:41.926+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:06:41.928+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:06:41.928+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:06:41.931+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:06:41.931+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:06:41.931+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:06:41.931+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:06:41.931+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:06:41.943+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:07:32.328+0000] {processor.py:157} INFO - Started process (PID=13436) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:07:32.329+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:07:32.331+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:32.331+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:07:32.335+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:32.334+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:07:32.335+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:07:32.335+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:07:32.335+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:07:32.348+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T15:08:22.638+0000] {processor.py:157} INFO - Started process (PID=13592) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:08:22.639+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:08:22.641+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:22.641+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:08:22.645+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:22.644+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:08:22.645+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:08:22.645+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:08:22.645+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:08:22.658+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T15:09:11.635+0000] {processor.py:157} INFO - Started process (PID=13848) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:09:11.636+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:09:11.639+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:11.638+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:09:11.642+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:11.641+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:09:11.642+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:09:11.642+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:09:11.642+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:09:11.654+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:10:02.334+0000] {processor.py:157} INFO - Started process (PID=14001) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:02.336+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:10:02.338+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:02.338+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:02.341+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:02.341+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:10:02.342+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:02.342+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:10:02.342+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:02.354+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-06-14T15:10:53.089+0000] {processor.py:157} INFO - Started process (PID=14095) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:53.090+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:10:53.093+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:53.093+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:53.096+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:53.095+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:10:53.096+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:10:53.096+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:10:53.096+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:10:53.108+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:11:39.399+0000] {processor.py:157} INFO - Started process (PID=14207) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:11:39.401+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:11:39.403+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:11:39.403+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:11:39.406+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:11:39.406+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:11:39.406+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:11:39.406+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:11:39.407+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:11:39.418+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:12:32.293+0000] {processor.py:157} INFO - Started process (PID=14369) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:12:32.294+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:12:32.297+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:32.297+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:12:32.300+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:32.299+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:12:32.300+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:12:32.300+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:12:32.300+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:12:32.312+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:13:25.117+0000] {processor.py:157} INFO - Started process (PID=14525) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:13:25.119+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:13:25.121+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:13:25.121+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:13:25.124+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:13:25.124+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:13:25.124+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:13:25.124+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:13:25.125+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:13:25.136+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-06-14T15:14:15.679+0000] {processor.py:157} INFO - Started process (PID=14784) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:14:15.681+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:14:15.685+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:15.684+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:14:15.690+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:15.689+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:14:15.690+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:14:15.690+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:14:15.690+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:14:15.702+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-06-14T15:15:04.513+0000] {processor.py:157} INFO - Started process (PID=14936) to work on /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:15:04.515+0000] {processor.py:826} INFO - Processing file /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-14T15:15:04.517+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:04.517+0000] {dagbag.py:541} INFO - Filling up the DagBag from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:15:04.520+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:04.519+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-14T15:15:04.520+0000] {logging_mixin.py:149} INFO - [2023-06-14T15:15:04.520+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-14T15:15:04.521+0000] {processor.py:838} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-14T15:15:04.533+0000] {processor.py:179} INFO - Processing /usr/local/lib/python3.8/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
