[2023-06-22T11:48:36.713+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:47:59.688254+00:00 [queued]>
[2023-06-22T11:48:36.722+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:47:59.688254+00:00 [queued]>
[2023-06-22T11:48:36.722+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-22T11:48:36.770+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_task.source.development.sales_stage.customers> on 2023-06-22 11:47:59.688254+00:00
[2023-06-22T11:48:36.775+0000] {standard_task_runner.py:57} INFO - Started process 83780 to run task
[2023-06-22T11:48:36.781+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt', 'dbt_task.source.development.sales_stage.customers', 'manual__2023-06-22T11:47:59.688254+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp911vpzwp']
[2023-06-22T11:48:36.782+0000] {standard_task_runner.py:85} INFO - Job 224: Subtask dbt_task.source.development.sales_stage.customers
[2023-06-22T11:48:36.851+0000] {task_command.py:410} INFO - Running <TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:47:59.688254+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-22T11:48:37.103+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt' AIRFLOW_CTX_TASK_ID='dbt_task.source.development.sales_stage.customers' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T11:47:59.688254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T11:47:59.688254+00:00'
[2023-06-22T11:48:37.104+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T11:48:37.105+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "cd /home/satyam/airflow/dags/dbt/ && dbt run --models bronze_customers --vars 'run_date: 2023-06-22T00:00:00+00:00'"]
[2023-06-22T11:48:37.113+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T11:48:39.610+0000] {subprocess.py:93} INFO - [0m11:48:39  Running with dbt=1.5.1
[2023-06-22T11:48:40.009+0000] {subprocess.py:93} INFO - [0m11:48:40  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-22T11:48:40.009+0000] {subprocess.py:93} INFO - There are 3 unused configuration paths:
[2023-06-22T11:48:40.009+0000] {subprocess.py:93} INFO - - models.development.staging
[2023-06-22T11:48:40.009+0000] {subprocess.py:93} INFO - - models.development.bronze
[2023-06-22T11:48:40.009+0000] {subprocess.py:93} INFO - - models.development.intermediate
[2023-06-22T11:48:40.027+0000] {subprocess.py:93} INFO - [0m11:48:40  Found 7 models, 0 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 4 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T11:48:40.029+0000] {subprocess.py:93} INFO - [0m11:48:40
[2023-06-22T11:48:41.283+0000] {subprocess.py:93} INFO - [0m11:48:41  Concurrency: 1 threads (target='dev')
[2023-06-22T11:48:41.284+0000] {subprocess.py:93} INFO - [0m11:48:41
[2023-06-22T11:48:41.290+0000] {subprocess.py:93} INFO - [0m11:48:41  1 of 1 START sql incremental model final_sales.bronze_customers ................ [RUN]
[2023-06-22T11:48:41.870+0000] {subprocess.py:93} INFO - [0m11:48:41  1 of 1 ERROR creating sql incremental model final_sales.bronze_customers ....... [[31mERROR[0m in 0.58s]
[2023-06-22T11:48:41.875+0000] {subprocess.py:93} INFO - [0m11:48:41
[2023-06-22T11:48:41.875+0000] {subprocess.py:93} INFO - [0m11:48:41  Finished running 1 incremental model in 0 hours 0 minutes and 1.84 seconds (1.84s).
[2023-06-22T11:48:41.886+0000] {subprocess.py:93} INFO - [0m11:48:41
[2023-06-22T11:48:41.886+0000] {subprocess.py:93} INFO - [0m11:48:41  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-22T11:48:41.887+0000] {subprocess.py:93} INFO - [0m11:48:41
[2023-06-22T11:48:41.887+0000] {subprocess.py:93} INFO - [0m11:48:41  [33mDatabase Error in model bronze_customers (models/sales/bronze/bronze_customers.sql)[0m
[2023-06-22T11:48:41.888+0000] {subprocess.py:93} INFO - [0m11:48:41    001003 (42000): SQL compilation error:
[2023-06-22T11:48:41.888+0000] {subprocess.py:93} INFO - [0m11:48:41    syntax error line 7 at position 16 unexpected '00'.
[2023-06-22T11:48:41.889+0000] {subprocess.py:93} INFO - [0m11:48:41    syntax error line 7 at position 28 unexpected '00'.
[2023-06-22T11:48:41.889+0000] {subprocess.py:93} INFO - [0m11:48:41    compiled Code at target/run/development/models/sales/bronze/bronze_customers.sql
[2023-06-22T11:48:41.890+0000] {subprocess.py:93} INFO - [0m11:48:41
[2023-06-22T11:48:41.890+0000] {subprocess.py:93} INFO - [0m11:48:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-06-22T11:48:43.169+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-22T11:48:43.177+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-22T11:48:43.180+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=airflow_dbt, task_id=dbt_task.source.development.sales_stage.customers, execution_date=20230622T114759, start_date=20230622T114836, end_date=20230622T114843
[2023-06-22T11:48:43.210+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 224 for task dbt_task.source.development.sales_stage.customers (Bash command failed. The command returned a non-zero exit code 1.; 83780)
[2023-06-22T11:48:43.246+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T11:48:43.378+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
