[2023-06-22T11:41:56.116+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:36:16.320737+00:00 [queued]>
[2023-06-22T11:41:56.125+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:36:16.320737+00:00 [queued]>
[2023-06-22T11:41:56.125+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-22T11:41:56.147+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_task.source.development.sales_stage.customers> on 2023-06-22 11:36:16.320737+00:00
[2023-06-22T11:41:56.153+0000] {standard_task_runner.py:57} INFO - Started process 81655 to run task
[2023-06-22T11:41:56.158+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt', 'dbt_task.source.development.sales_stage.customers', 'manual__2023-06-22T11:36:16.320737+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpfv_sm_p2']
[2023-06-22T11:41:56.158+0000] {standard_task_runner.py:85} INFO - Job 219: Subtask dbt_task.source.development.sales_stage.customers
[2023-06-22T11:41:56.215+0000] {task_command.py:410} INFO - Running <TaskInstance: airflow_dbt.dbt_task.source.development.sales_stage.customers manual__2023-06-22T11:36:16.320737+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-22T11:41:56.455+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt' AIRFLOW_CTX_TASK_ID='dbt_task.source.development.sales_stage.customers' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T11:36:16.320737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T11:36:16.320737+00:00'
[2023-06-22T11:41:56.456+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-22T11:41:56.457+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "cd /home/satyam/airflow/dags/dbt/ && dbt run --models bronze_customers --vars 'run_date: 2023-06-22T00:00:00+00:00'"]
[2023-06-22T11:41:56.464+0000] {subprocess.py:86} INFO - Output:
[2023-06-22T11:41:58.922+0000] {subprocess.py:93} INFO - [0m11:41:58  Running with dbt=1.5.1
[2023-06-22T11:41:59.329+0000] {subprocess.py:93} INFO - [0m11:41:59  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-22T11:41:59.329+0000] {subprocess.py:93} INFO - There are 3 unused configuration paths:
[2023-06-22T11:41:59.329+0000] {subprocess.py:93} INFO - - models.development.bronze
[2023-06-22T11:41:59.330+0000] {subprocess.py:93} INFO - - models.development.intermediate
[2023-06-22T11:41:59.330+0000] {subprocess.py:93} INFO - - models.development.staging
[2023-06-22T11:41:59.349+0000] {subprocess.py:93} INFO - [0m11:41:59  Found 7 models, 0 tests, 0 snapshots, 0 analyses, 321 macros, 0 operations, 0 seed files, 4 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-22T11:41:59.351+0000] {subprocess.py:93} INFO - [0m11:41:59
[2023-06-22T11:42:01.051+0000] {subprocess.py:93} INFO - [0m11:42:01  Concurrency: 1 threads (target='dev')
[2023-06-22T11:42:01.051+0000] {subprocess.py:93} INFO - [0m11:42:01
[2023-06-22T11:42:01.057+0000] {subprocess.py:93} INFO - [0m11:42:01  1 of 1 START sql incremental model final_sales.bronze_customers ................ [RUN]
[2023-06-22T11:42:01.508+0000] {subprocess.py:93} INFO - [0m11:42:01  1 of 1 ERROR creating sql incremental model final_sales.bronze_customers ....... [[31mERROR[0m in 0.45s]
[2023-06-22T11:42:01.512+0000] {subprocess.py:93} INFO - [0m11:42:01
[2023-06-22T11:42:01.513+0000] {subprocess.py:93} INFO - [0m11:42:01  Finished running 1 incremental model in 0 hours 0 minutes and 2.16 seconds (2.16s).
[2023-06-22T11:42:01.522+0000] {subprocess.py:93} INFO - [0m11:42:01
[2023-06-22T11:42:01.523+0000] {subprocess.py:93} INFO - [0m11:42:01  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-22T11:42:01.524+0000] {subprocess.py:93} INFO - [0m11:42:01
[2023-06-22T11:42:01.524+0000] {subprocess.py:93} INFO - [0m11:42:01  [33mDatabase Error in model bronze_customers (models/sales/bronze/bronze_customers.sql)[0m
[2023-06-22T11:42:01.525+0000] {subprocess.py:93} INFO - [0m11:42:01    001003 (42000): SQL compilation error:
[2023-06-22T11:42:01.525+0000] {subprocess.py:93} INFO - [0m11:42:01    syntax error line 7 at position 16 unexpected '00'.
[2023-06-22T11:42:01.526+0000] {subprocess.py:93} INFO - [0m11:42:01    syntax error line 7 at position 28 unexpected '00'.
[2023-06-22T11:42:01.526+0000] {subprocess.py:93} INFO - [0m11:42:01    compiled Code at target/run/development/models/sales/bronze/bronze_customers.sql
[2023-06-22T11:42:01.527+0000] {subprocess.py:93} INFO - [0m11:42:01
[2023-06-22T11:42:01.527+0000] {subprocess.py:93} INFO - [0m11:42:01  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-06-22T11:42:02.806+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-22T11:42:02.813+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-22T11:42:02.816+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=airflow_dbt, task_id=dbt_task.source.development.sales_stage.customers, execution_date=20230622T113616, start_date=20230622T114156, end_date=20230622T114202
[2023-06-22T11:42:02.840+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 219 for task dbt_task.source.development.sales_stage.customers (Bash command failed. The command returned a non-zero exit code 1.; 81655)
[2023-06-22T11:42:02.858+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T11:42:02.982+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
