[2023-06-20T20:24:20.498+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt.model.development.bronze_orders manual__2023-06-20T20:24:17.367211+00:00 [queued]>
[2023-06-20T20:24:20.505+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt.model.development.bronze_orders manual__2023-06-20T20:24:17.367211+00:00 [queued]>
[2023-06-20T20:24:20.505+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-20T20:24:20.531+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): model.development.bronze_orders> on 2023-06-20 20:24:17.367211+00:00
[2023-06-20T20:24:20.535+0000] {standard_task_runner.py:57} INFO - Started process 16890 to run task
[2023-06-20T20:24:20.539+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt', 'model.development.bronze_orders', 'manual__2023-06-20T20:24:17.367211+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpxpk09klg']
[2023-06-20T20:24:20.540+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask model.development.bronze_orders
[2023-06-20T20:24:20.595+0000] {task_command.py:410} INFO - Running <TaskInstance: airflow_dbt.model.development.bronze_orders manual__2023-06-20T20:24:17.367211+00:00 [running]> on host ubuntu.thbnzb0d3dmuziyfg2t53bofqb.tx.internal.cloudapp.net
[2023-06-20T20:24:20.861+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt' AIRFLOW_CTX_TASK_ID='model.development.bronze_orders' AIRFLOW_CTX_EXECUTION_DATE='2023-06-20T20:24:17.367211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-20T20:24:17.367211+00:00'
[2023-06-20T20:24:20.863+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T20:24:20.863+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                cd /home/satyam/airflow/dags/dbt/ &&\n                dbt --no-write-json run --target prod --models bronze_orders\n                ']
[2023-06-20T20:24:20.872+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T20:24:23.291+0000] {subprocess.py:93} INFO - [0m20:24:23  Running with dbt=1.5.1
[2023-06-20T20:24:23.296+0000] {subprocess.py:93} INFO - [0m20:24:23  Encountered an error:
[2023-06-20T20:24:23.296+0000] {subprocess.py:93} INFO - Runtime Error
[2023-06-20T20:24:23.296+0000] {subprocess.py:93} INFO -   The profile 'default' does not have a target named 'prod'. The valid target names for this profile are:
[2023-06-20T20:24:23.296+0000] {subprocess.py:93} INFO -    - dev
[2023-06-20T20:24:24.669+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-20T20:24:24.677+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-20T20:24:24.680+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=airflow_dbt, task_id=model.development.bronze_orders, execution_date=20230620T202417, start_date=20230620T202420, end_date=20230620T202424
[2023-06-20T20:24:24.703+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 165 for task model.development.bronze_orders (Bash command failed. The command returned a non-zero exit code 2.; 16890)
[2023-06-20T20:24:24.726+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-20T20:24:24.748+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
